services:
  postgres:
    image: postgres:16-alpine
    container_name: ff_postgres
    environment:
      POSTGRES_DB: feature_flag_db
      POSTGRES_USER: ff_user
      POSTGRES_PASSWORD: ff_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ff_user -d feature_flag_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
